### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by hikkyu** [webpro/knip#281]
Hi there!

I work on a very big monorepo, and I encountered an issue when I run these commands with the latest version (2.30.1):

`npx knip --no-gitignore`

As we have multiple workspaces also tried just in one workspace (around 1000 files to analyze):
`npx knip --no-gitignore --workspace apps/fr-app --exports`

But I got a Heap of memory then I tried

`NODE_OPTIONS=--max-old-space-size=5120 npx knip --no-gitignore --workspace apps/fr-app --exports`

Also tried without `npx` with script in the `package.json`

But in any case, I always get this error:

```bash
file:///<my-project-path>/node_modules/knip/dist/typescript/getImportsAndExports.js:120
                const results = visitor(node, options);
                                ^
RangeError: Maximum call stack size exceeded
    at file:///<my-project-path>/node_modules/knip/dist/typescript/visitors/imports/jsDocType.js:4:34
    at file:///<my-project-path>/node_modules/knip/dist/typescript/visitors/index.js:4:35
    at visit (file:///<my-project-path>/node_modules/knip/dist/typescript/getImportsAndExports.js:120:33)
    at visitNode2 (/<my-project-path>/node_modules/typescript/lib/typescript.js:27926:20)
    at forEachChildInPropertyAccessExpression (/<my-project-path>/node_modules/typescript/lib/typescript.js:28495:18)
    at Object.forEachChild (/<my-project-path>/node_modules/typescript/lib/typescript.js:28019:37)
    at visit (file:///<my-project-path>/node_modules/knip/dist/typescript/getImportsAndExports.js:145:12)
    at visitNode2 (/<my-project-path>/node_modules/typescript/lib/typescript.js:27926:20)
    at forEachChildInCallOrNewExpression (/<my-project-path>/node_modules/typescript/lib/typescript.js:27975:12)
    at Object.forEachChild (/<my-project-path>/node_modules/typescript/lib/typescript.js:28019:37)
```

Additional information: I didn't setup a knip config file, I used the default config only.

Does it ring a bell? Tell me if you need more information 🙂

**Comment by webpro** [comment]
No, doesn't ring a 🔔 unfortunately. Without a reproduction there isn't much I can see/do.

Most likely an infinite recursion and/or cyclic dependency.

**Comment by stackptr** [comment]
A variation of this error was caused in my project by a circular dependency. I was able to setup `madge` to analyze the dependency tree and fix the issue.

I wonder if there is anything useful that could be logged for debugging this scenario?

**Comment by webpro** [comment]
I've released v2.31.0 which _might_ fix it (probably not, though).

Otherwise I'll need a reproduction.

Using `--debug` probably doesn't give that much, but might at least show where in the process and/or in which workspace Knip is currently running.

**Comment by webpro** [comment]
Closing this due to inactivity. Feel free to discuss further or open a new issue. Note that I'd need a reproduction.

**Comment by lgodziejewski** [comment]
I have the same issue on the newest version (`2.40.0`) - first it was OoM, so I've added `NODE_OPTIONS=--max-old-space-size=11776`

now `RangeError: Maximum call stack size exceeded` 😢.

can't really give a repro, since it's a company project. I'll try to find out if there's a circular dependency, as mentioned above

**Comment by webpro** [comment]
Knip v4 is about to mitigate some of these issues: https://knip.dev/blog/slim-down-to-speed-up (you can install and try v4 canary today). Recently added [--isolate-workspaces](https://knip.dev/reference/cli/#--isolate-workspaces) (in v3) which may also help in certain edge cases.
