### ISSUE TITLE
TypeError when runing knip for the first time

### ISSUE THREAD

**Issue by bryanjtc** [webpro/knip#282]
TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (C:\Projects\PayMeSoftWeb\reactapp\node_modules\path-scurry\dist\cjs\index.js:131:40)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at loaders.<computed>.Module._extensions.<computed> [as .js] 

Node.js v18.12.1

**Comment by webpro** [comment]
That doesn't provide much information. Perhaps a run using `--debug` gives you more interesting output?

**Comment by bryanjtc** [comment]
> That doesn't provide much information. Perhaps a run using `--debug` gives you more interesting output?

 yarn run knip --debug
C:\Projects\PayMeSoftWeb\reactapp\node_modules\path-scurry\dist\cjs\index.js:131
class ResolveCache extends lru_cache_1.LRUCache {
                                       ^

TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (C:\Projects\PayMeSoftWeb\reactapp\node_modules\path-scurry\dist\cjs\index.js:131:40)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at loaders.<computed>.Module._extensions.<computed> [as .js] (C:\Projects\PayMeSoftWeb\reactapp\node_modules\jiti\dist\jiti.js:1:16777)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\Projects\PayMeSoftWeb\reactapp\node_modules\glob\dist\cjs\src\glob.js:5:23)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)

Node.js v18.12.1

**Comment by webpro** [comment]
Do you have a reproduction maybe? How or why is `path-scurry` loaded?

**Comment by bryanjtc** [comment]
I tried to create a reproduction of the error and it worked fine. It seems deleting node_modules and reinstalling fixed the problem.
