### ISSUE TITLE
findPostCssDependencies results in error when using autoprefixer

### ISSUE THREAD

**Issue by Aaronkala** [webpro/knip#29]
I'm getting the following error in knip@1.0.0-beta.1

```
/node_modules/knip/dist/util/modules.js:6
    const match = value.replace(/\\/g, '/').match(/(?<=node_modules\/)(@[^/]+\/[^/]+|[^/]+)/);
                        ^

TypeError: value.replace is not a function
    at getPackageName (/node_modules/knip/dist/util/modules.js:6:25)
    at Array.map (<anonymous>)
    at findPostCSSDependencies (/node_modules/knip/dist/plugins/postcss/index.js:13:90)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /node_modules/knip/dist/workspace-worker.js:232:34
    at async Promise.all (index 0)
    at async WorkspaceWorker.findDependenciesByPlugin (/node_modules/knip/dist/workspace-worker.js:231:45)
    at async WorkspaceWorker.findDependenciesByPlugins (/node_modules/knip/dist/workspace-worker.js:209:42)
    at async main (/node_modules/knip/dist/index.js:179:80)
    at async run (/node_modules/knip/dist/cli.js:21:46)
```

It seems to break when reading the package name from `postcss.config.js`

Our postcss.config.js contains the autoprefixer import which is a function instead of a string :)
```js
module.exports = {
  plugins: [require('autoprefixer')],
};
```

**Comment by webpro** [comment]
Ah yes, the postcss plugin didn't have (default) entry files yet, they're added in the latest beta :)

**Comment by Aaronkala** [comment]
Awesome thanks 🙌  Great library btw! The best tool I've found for finding unused code 👍

**Comment by Aaronkala** [comment]
Tested the latest release and it fixed the issue for me 🙏
