### ISSUE TITLE
Does not support Storybook stories config object syntax

### ISSUE THREAD

**Issue by IanVS** [webpro/knip#312]
Storybook's `stories` array can accept not only globs, but also config objects: https://storybook.js.org/docs/react/api/main-config-stories#with-a-configuration-object

However, if that is being used, knip throws an exception.

```
Analyzing workspace ....
node:internal/errors:490
    ErrorCaptureStackTrace(err);
    ^

TypeError: The "path" argument must be of type string. Received an instance of Object
    at new NodeError (node:internal/errors:399:5)
    at validateString (node:internal/validators:163:11)
    at join (node:path:1172:7)
    at file:///Users/ianvs/Library/pnpm/store/v3/tmp/dlx-50914/node_modules/.pnpm/knip@2.38.0/node_modules/knip/dist/plugins/storybook/index.js:18:68
    at Array.map (<anonymous>)
    at Module.findStorybookDependencies (file:///Users/ianvs/Library/pnpm/store/v3/tmp/dlx-50914/node_modules/.pnpm/knip@2.38.0/node_modules/knip/dist/plugins/storybook/index.js:18:39)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async WorkspaceWorker.findDependenciesByPlugins (file:///Users/ianvs/Library/pnpm/store/v3/tmp/dlx-50914/node_modules/.pnpm/knip@2.38.0/node_modules/knip/dist/WorkspaceWorker.js:191:46)
    at async WorkspaceWorker.findAllDependencies (file:///Users/ianvs/Library/pnpm/store/v3/tmp/dlx-50914/node_modules/.pnpm/knip@2.38.0/node_modules/knip/dist/WorkspaceWorker.js:216:9)
    at async main (file:///Users/ianvs/Library/pnpm/store/v3/tmp/dlx-50914/node_modules/.pnpm/knip@2.38.0/node_modules/knip/dist/index.js:109:30)
    at async run (file:///Users/ianvs/Library/pnpm/store/v3/tmp/dlx-50914/node_modules/.pnpm/knip@2.38.0/node_modules/knip/dist/cli.js:24:73)
    at async file:///Users/ianvs/Library/pnpm/store/v3/tmp/dlx-50914/node_modules/.pnpm/knip@2.38.0/node_modules/knip/dist/cli.js:74:1 {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v18.16.0
```

Reproduction: https://stackblitz.com/edit/github-z465pp?file=package.json

Stop the storybook, and run `npm run knip` to see the error.

**Comment by webpro** [comment]
I'm seeing this pattern:

```ts
  stories: [
    '../src/**/*.mdx',
    {
      directory: '../src',
    },
  ]
```

But isn't it a bit odd? Why is it not more like so:

```ts
  stories: [
    '../src/**/*.stories.js',
    {
      files: '**/*.mdx',
      directory: '../src',
    },
  ],
```

A string/glob is fine, but if an object is used then `files` should be set too?

**Comment by IanVS** [comment]
`files` does not need to be set, there is a default of `'**/*.@(mdx|stories.@(mdx|js|jsx|mjs|ts|tsx))'`

See: https://storybook.js.org/docs/react/api/main-config-stories#storiesspecifierfiles

**Comment by webpro** [comment]
Ah, right, sorry I interpreted as if there was some kind of connection between `'../src/**/*.mdx'` and `directory: '../src'`, but they are just separate things and `files` has a default. Gotcha :)

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v2.38.1. See [Release 2.38.1](https://github.com/webpro/knip/releases/tag/2.38.1) for release notes._

**Comment by webpro** [comment]
Thanks, Ian!

**Comment by IanVS** [comment]
That was fast, thanks!  Sorry for the confusing reproduction.
