### ISSUE TITLE
TypeError: specifier.startsWith is not a function

### ISSUE THREAD

**Issue by AbhiPrasad** [webpro/knip#357]
Running on https://github.com/getsentry/sentry-javascript. Node 18.17.0, using knip @ 2.41.5 running in workspace root.

```
~/workspace/sentry-javascript (develop) » npx knip@2.41.5                                                          abhijeetprasad@GT9RQ02WW5
Need to install the following packages:
  knip@2.41.5
Ok to proceed? (y) y
Analyzing workspace packages/ember...
file:///Users/abhijeetprasad/.npm/_npx/c0076afb8fa90a3f/node_modules/knip/dist/util/protocols.js:6
export const isEntryPattern = (specifier) => specifier.startsWith('entry:');
                                                       ^

TypeError: specifier.startsWith is not a function
    at isEntryPattern (file:///Users/abhijeetprasad/.npm/_npx/c0076afb8fa90a3f/node_modules/knip/dist/util/protocols.js:6:56)
    at file:///Users/abhijeetprasad/.npm/_npx/c0076afb8fa90a3f/node_modules/knip/dist/WorkspaceWorker.js:199:33
    at Array.forEach (<anonymous>)
    at WorkspaceWorker.findDependenciesByPlugins (file:///Users/abhijeetprasad/.npm/_npx/c0076afb8fa90a3f/node_modules/knip/dist/WorkspaceWorker.js:197:38)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async WorkspaceWorker.findAllDependencies (file:///Users/abhijeetprasad/.npm/_npx/c0076afb8fa90a3f/node_modules/knip/dist/WorkspaceWorker.js:216:9)
    at async main (file:///Users/abhijeetprasad/.npm/_npx/c0076afb8fa90a3f/node_modules/knip/dist/index.js:110:30)
    at async run (file:///Users/abhijeetprasad/.npm/_npx/c0076afb8fa90a3f/node_modules/knip/dist/cli.js:24:73)
    at async file:///Users/abhijeetprasad/.npm/_npx/c0076afb8fa90a3f/node_modules/knip/dist/cli.js:74:1

Node.js v18.17.0
```

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v2.41.6. See [Release 2.41.6](https://github.com/webpro/knip/releases/tag/2.41.6) for release notes._

**Comment by webpro** [comment]
Thanks for the report, @AbhiPrasad! Should be good now.

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v3.0.0-canary.4. See [Release 3.0.0-canary.4](https://github.com/webpro/knip/releases/tag/3.0.0-canary.4) for release notes._

**Comment by gongtiexin** [comment]
```
export const isEntryPattern = (specifier) => specifier.startsWith('entry:');
                                                       ^
TypeError: specifier.startsWith is not a function
```
I got this error in the latest version. Node.js v18.20.0  knip@5.11.0

**Comment by webpro** [comment]
@gongtiexin  Would be good to know where that `specifier` is coming from (perhaps a new plugin). Any chance you could use `knip --debug` to hopefully get a better idea about this?

**Comment by gongtiexin** [comment]
Mainly I want to know what configurations are there. It’s not convenient to post debug logs directly. V5.8.0 works for me.

**Comment by RafalFilipek** [comment]
@webpro I just updated to the latest version and I have similar issue. 

```
[ '/[---redacted---]/commitlint.config.js' ]
{ rules: { 'contains-issue': [Function: contains-issue] } }
file:///[---redacted---]/node_modules/knip/dist/util/protocols.js:8
  return specifier.startsWith('entry:');
                   ^

TypeError: specifier.startsWith is not a function
    at isEntryPattern (file:///[---redacted---]/node_modules/knip/dist/util/protocols.js:8:20)
    at addDependency (file:///[---redacted---]/node_modules/knip/dist/WorkspaceWorker.js:184:25)
    at WorkspaceWorker.findDependenciesByPlugins (file:///[---redacted---]/node_modules/knip/dist/WorkspaceWorker.js:212:37)
    at async main (file:///[---redacted---]/node_modules/knip/dist/index.js:106:108)
    at async run (file:///[---redacted---]/node_modules/knip/dist/cli.js:23:73)
    at async file:///[---redacted---]/node_modules/knip/dist/cli.js:90:1
```

It looks like there is a problem with custom rules in commitlint config


```
/**
 * @type {import('@commitlint/types').UserConfig}
 */
const config = {
  rules: {
    "type-enum": [2, "always", ["fix", "feat", "chore"]],
    "contains-issue": [2, "always"],
  },
  plugins: [
    {
      rules: {
        "contains-issue": ({ subject }) => {
          // redacted
        },
      },
    },
  ],
};

export default config;
```
