### ISSUE TITLE
TypeError on parsing file

### ISSUE THREAD

**Issue by fxOne** [webpro/knip#42]
I'm getting the following error:

```bash
/var/www/html/packages/myProject/babel.config.js:41
  api.cache(true);
      ^


TypeError: api.cache is not a function
    at module.exports (/var/www/html/packages/myProject/babel.config.js:41:7)
    at findBabelDependencies (file:///var/www/html/node_modules/knip/dist/plugins/babel/index.js:32:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///var/www/html/node_modules/knip/dist/workspace-worker.js:228:34
    at async Promise.all (index 0)
    at async WorkspaceWorker.findDependenciesByPlugin (file:///var/www/html/node_modules/knip/dist/workspace-worker.js:227:45)
    at async WorkspaceWorker.findDependenciesByPlugins (file:///var/www/html/node_modules/knip/dist/workspace-worker.js:205:42)
    at async main (file:///var/www/html/node_modules/knip/dist/index.js:184:80)
    at async run (file:///var/www/html/node_modules/knip/dist/cli.js:20:46)
    at async file:///var/www/html/node_modules/knip/dist/cli.js:47:1
```

The content of the file is:

```js
...
module.exports = function (api) {
  api.cache(true);

  return {
    env: {
      test: {
        plugins: testPlugins,
        //'presets': presets,
        compact: false,
        comments: true,
        sourceMaps: true,
      },
    },
  };
};
```
It somehow looks like this file is being executed.

**Comment by webpro** [comment]
> It somehow looks like this file is being executed.

Indeed, this file needs to be executed in order to parse the resulting Babel configuration. This configuration can contain plugin references as strings like `preval` and `@babel/plugin-syntax-dynamic-import`, which are translated to `babel-plugin-preval` etc. so Knip can see whether such dependencies are either unused or missing.

In the case of Babel, it's an extra bit of complexity that it's not just a "configuration as a function", but also with an `api` object argument. This had a too minimal implementation in the babel plugin, hence your issue.

I'll get to it shortly, thanks for reporting!
