### ISSUE TITLE
Crash parsing the withNx webpack helper

### ISSUE THREAD

**Issue by roderik** [webpro/knip#467]
Ran knip as a test on a standard NX.dev workspace with nest and next apps, but it fails on the withNx webpack helper in the node_modules folder. (ran it at the top level)

```
Analyzing workspace apps/shared/api...
/Users/roderik/Development/bpaas/node_modules/.pnpm/@nx+webpack@17.2.8_@swc+core@1.3.104_@types+node@20.11.5_nx@17.2.8_typescript@5.3.3_webpack-cli@5.1.4/node_modules/@nx/webpack/src/utils/with-nx.js:18
            assets: options.assets
                            ^

TypeError: Cannot read properties of undefined (reading 'assets')
    at configure (/Users/roderik/Development/bpaas/node_modules/.pnpm/@nx+webpack@17.2.8_@swc+core@1.3.104_@types+node@20.11.5_nx@17.2.8_typescript@5.3.3_webpack-cli@5.1.4/node_modules/@nx/webpack/src/utils/with-nx.js:18:29)
    at combined (/Users/roderik/Development/bpaas/node_modules/.pnpm/@nx+webpack@17.2.8_@swc+core@1.3.104_@types+node@20.11.5_nx@17.2.8_typescript@5.3.3_webpack-cli@5.1.4/node_modules/@nx/webpack/src/utils/config.js:23:28)
    at async findWebpackDependenciesFromConfig (file:///Users/roderik/Development/bpaas/node_modules/.pnpm/knip@4.1.0_@types+node@20.11.5_typescript@5.3.3/node_modules/knip/dist/plugins/webpack/index.js:54:63)
    at async Object.findWebpackDependencies [as findDependencies] (file:///Users/roderik/Development/bpaas/node_modules/.pnpm/knip@4.1.0_@types+node@20.11.5_typescript@5.3.3/node_modules/knip/dist/plugins/webpack/index.js:95:45)
    at async WorkspaceWorker.findDependenciesByPlugins (file:///Users/roderik/Development/bpaas/node_modules/.pnpm/knip@4.1.0_@types+node@20.11.5_typescript@5.3.3/node_modules/knip/dist/WorkspaceWorker.js:192:46)
    at async WorkspaceWorker.findAllDependencies (file:///Users/roderik/Development/bpaas/node_modules/.pnpm/knip@4.1.0_@types+node@20.11.5_typescript@5.3.3/node_modules/knip/dist/WorkspaceWorker.js:218:9)
    at async main (file:///Users/roderik/Development/bpaas/node_modules/.pnpm/knip@4.1.0_@types+node@20.11.5_typescript@5.3.3/node_modules/knip/dist/index.js:127:30)
    at async run (file:///Users/roderik/Development/bpaas/node_modules/.pnpm/knip@4.1.0_@types+node@20.11.5_typescript@5.3.3/node_modules/knip/dist/cli.js:24:73)
    at async file:///Users/roderik/Development/bpaas/node_modules/.pnpm/knip@4.1.0_@types+node@20.11.5_typescript@5.3.3/node_modules/knip/dist/cli.js:79:1

Node.js v21.6.0
```

**Comment by webpro** [comment]
Any chance you could share (the relevant part of) that (redacted) file?

**Comment by roderik** [comment]
NX adds the following webpack files in a project

```
const { composePlugins, withNx } = require('@nx/webpack');

// Nx plugins for webpack.
module.exports = composePlugins(
  withNx({
    target: 'node',
  }),
  (config) => {
    return config;
  }
);
```

and withNX looks like this

```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.withNx = void 0;
const apply_base_config_1 = require("../plugins/nx-webpack-plugin/lib/apply-base-config");
const normalize_options_1 = require("../plugins/nx-webpack-plugin/lib/normalize-options");
const processed = new Set();
/**
 * @param {WithNxOptions} pluginOptions
 * @returns {NxWebpackPlugin}
 */
function withNx(pluginOptions = {}) {
    return function configure(config, { options, context }) {
        if (processed.has(config))
            return config;
        (0, apply_base_config_1.applyBaseConfig)({
            ...options,
            ...pluginOptions,
            assets: options.assets
                ? options.assets
                : pluginOptions.assets
                    ? (0, normalize_options_1.normalizeAssets)(pluginOptions.assets, options.root, options.sourceRoot)
                    : [],
            root: context.root,
            projectName: context.projectName,
            targetName: context.targetName,
            configurationName: context.configurationName,
            projectGraph: context.projectGraph,
        }, config);
        processed.add(config);
        return config;
    };
}
exports.withNx = withNx;
```

**Comment by webpro** [comment]
I would need some proper reproduction, the issue isn't obvious to me as there are Nx internals involved.

**Comment by roderik** [comment]
Latest knip + latest nx works!

**Comment by webpro** [comment]
The best issues are the issues that solve themselves ✨
