### ISSUE TITLE
Knip crashes when running in a pnpm monorepo where a workspace package folder is empty

### ISSUE THREAD

**Issue by jazmon** [webpro/knip#594]
Knip crashes if a `pnpm` monorepo has the following:
- workspaces enabled
- it's being run from the root ie. `pnpm knip --workspace services/my-api`
- one or more packages in the workspace are empty, except for the `node_modules` directory being present (this happens when you're creating a new package in one branch but change to a different branch)

Workaround is to manually remove the folder empty folder, ie. `rm -rf services/my-new-api`.

A possible fix would be to check if the folder has a package.json and only then count it as a workspace package.

Stacktrace:
```sh
$ pnpm knip --reporter markdown --include files,dependencies --workspace services/my-api
Reading workspace configuration(s)...
node:internal/modules/cjs/loader:1144
  const err = new Error(message);
              ^

Error: Cannot find module '/Users/atte/code/my-project/services/my-new-api/package.json'
Require stack:
- /Users/atte/code/my-project
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at file:///Users/atte/code/my-project/node_modules/.pnpm/knip@5.9.4_@types+node@20.10.7_typescript@5.3.3/node_modules/knip/dist/ConfigurationChief.js:216:30
    at Array.map (<anonymous>)
    at ConfigurationChief.getAvailableWorkspaceManifests (file:///Users/atte/code/my-project/node_modules/.pnpm/knip@5.9.4_@types+node@20.10.7_typescript@5.3.3/node_modules/knip/dist/ConfigurationChief.js:215:39)
    at ConfigurationChief.setWorkspaces (file:///Users/atte/code/my-project/node_modules/.pnpm/knip@5.9.4_@types+node@20.10.7_typescript@5.3.3/node_modules/knip/dist/ConfigurationChief.js:164:49)
    at async ConfigurationChief.init (file:///Users/atte/code/my-project/node_modules/.pnpm/knip@5.9.4_@types+node@20.10.7_typescript@5.3.3/node_modules/knip/dist/ConfigurationChief.js:101:9)
    at async main (file:///Users/atte/code/my-project/node_modules/.pnpm/knip@5.9.4_@types+node@20.10.7_typescript@5.3.3/node_modules/knip/dist/index.js:32:5)
    at async run (file:///Users/atte/code/my-project/node_modules/.pnpm/knip@5.9.4_@types+node@20.10.7_typescript@5.3.3/node_modules/knip/dist/cli.js:25:73)
    at async file:///Users/atte/code/my-project/node_modules/.pnpm/knip@5.9.4_@types+node@20.10.7_typescript@5.3.3/node_modules/knip/dist/cli.js:85:1 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/atte/code/my-project' ]
}

Node.js v20.11.0
```

**Comment by jazmon** [comment]
Seems to be fixed in `5.10.0-canary.1`, closing this
