### ISSUE TITLE
Commitlint plugin: specifier.startsWith is not a function

### ISSUE THREAD

**Issue by RafalFilipek** [webpro/knip#628]
Just updated to the latest version and I have an issue with commitlint. 

Reproduction: https://stackblitz.com/edit/github-puva2b?file=knip.json

```
[ '/[---redacted---]/commitlint.config.js' ]
{ rules: { 'contains-issue': [Function: contains-issue] } }
file:///[---redacted---]/node_modules/knip/dist/util/protocols.js:8
  return specifier.startsWith('entry:');
                   ^

TypeError: specifier.startsWith is not a function
    at isEntryPattern (file:///[---redacted---]/node_modules/knip/dist/util/protocols.js:8:20)
    at addDependency (file:///[---redacted---]/node_modules/knip/dist/WorkspaceWorker.js:184:25)
    at WorkspaceWorker.findDependenciesByPlugins (file:///[---redacted---]/node_modules/knip/dist/WorkspaceWorker.js:212:37)
    at async main (file:///[---redacted---]/node_modules/knip/dist/index.js:106:108)
    at async run (file:///[---redacted---]/node_modules/knip/dist/cli.js:23:73)
    at async file:///[---redacted---]/node_modules/knip/dist/cli.js:90:1
```

It looks like there is a problem with custom rules in commitlint config

```
/**
 * @type {import('@commitlint/types').UserConfig}
 */
const config = {
  rules: {
    "type-enum": [2, "always", ["fix", "feat", "chore"]],
    "contains-issue": [2, "always"],
  },
  plugins: [
    {
      rules: {
        "contains-issue": ({ subject }) => {
          // redacted
        },
      },
    },
  ],
};

export default config;
```

_Originally posted by @RafalFilipek in https://github.com/webpro/knip/issues/357#issuecomment-2102626044_

**Comment by webpro** [comment]
:rocket: _This issue has been resolved in v5.14.0. See [Release 5.14.0](https://github.com/webpro/knip/releases/tag/5.14.0) for release notes._

_Using Knip in a commercial project? Please consider [sponsoring me](https://github.com/sponsors/webpro)._
