### ISSUE TITLE
Add support for package self referencing

### ISSUE THREAD

**Issue by RebeccaStevens** [webpro/knip#87]
[package self-referencing](https://nodejs.org/api/packages.html#self-referencing-a-package-using-its-name) should be treated the same as local file imports.
re: https://github.com/webpro/knip/issues/77#issuecomment-1465139111

knip `2.0.0-alpha.8` crashes when it encounters a self-referencing import that needs to be looked up in the "exports" field of the "package.json" file.

```sh
> knip --exclude exports

Analyzing workspace (.)...
node:internal/modules/cjs/loader:1075
  const err = new Error(message);
              ^

Error: Cannot find module '/home/rebec/dev/eslint-config-rebeccastevens/script'
Require stack:
- /home/rebec/dev/eslint-config-rebeccastevens
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Function.resolve (node:internal/modules/cjs/helpers:116:19)
    at resolve (file:///home/rebec/dev/eslint-config-rebeccastevens/node_modules/.pnpm/knip@2.0.0-alpha.8/node_modules/knip/dist/util/require.js:5:48)
    at file:///home/rebec/dev/eslint-config-rebeccastevens/node_modules/.pnpm/knip@2.0.0-alpha.8/node_modules/knip/dist/index.js:144:42
    at Set.forEach (<anonymous>)
    at main (file:///home/rebec/dev/eslint-config-rebeccastevens/node_modules/.pnpm/knip@2.0.0-alpha.8/node_modules/knip/dist/index.js:123:32)
    at async run (file:///home/rebec/dev/eslint-config-rebeccastevens/node_modules/.pnpm/knip@2.0.0-alpha.8/node_modules/knip/dist/cli.js:26:46)
    at async file:///home/rebec/dev/eslint-config-rebeccastevens/node_modules/.pnpm/knip@2.0.0-alpha.8/node_modules/knip/dist/cli.js:57:1 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/rebec/dev/eslint-config-rebeccastevens' ]
}

Node.js v18.15.0
```

**Comment by webpro** [comment]
With v2 released I think we can close this issue :)
